### PR TITLE
Unit tests again

### PR DESCRIPTION
**Pull request by GigiDev7**
we had to create it for one module only but i also added unit tests for account endpoints

### CODE REVIEW

**Comment by GigiDev7** [comment]
should i have this test files in root folder? or in routes folder? or in seperate 'test' folder?

**Comment by GigiDev7** [comment]
well obviously not in the root folder

**Comment by GigiDev7** [comment]
finished all!

**Review by Lokki17 — APPROVED** [review]

**Comment by Lokki17** [comment]
> should i have this test files in root folder? or in routes folder? or in seperate 'test' folder?

up to you

**Comment by Lokki17** [comment]
> finished all!

well done. Create PR for tests but I will not check it. I know you want me to know that you added tests, I know :)

**Pull request merged**
